name: Build and Review PR
on:
  # This workflow uses the pull_request trigger which prevents write permissions on the
  # GH_TOKEN and secrets access from public forks.  This should remain as a pull_request
  # trigger to protect org-level secrets which are utilized when the workflow automatically
  # recompiles the action and updates the readme with the latest version changes in branches.
  # The reduced permissions for public forks is adequate but does mean re-compiles and readme
  # changes will have to be made manually when the PR comes from a fork.
  pull_request:
  # Don't include any specific paths here so we always get a build that produces a status
  # check that our Branch Protection Rules can use.  Having a status check also allows us
  # to require that branches be up to date before they are merged.

jobs:
  ci:
    uses: im-open/.github/.github/workflows/reusable-javascript-build.yml@v1
    with:
      action-name: ${{ github.repository }}
      default-branch: main
      readme-location: './README.md'
      files-with-code: 'action.yml,package.json,package-lock.json' # TODO:  Update if there are additional files or scripts that contain source code for the action
      folders-with-code: 'src,dist'                                # TODO:  Update if there are additional directories that contain source code for the action
      build-command: 'npm run build'                               # TODO:  Update if a different command is used to build/recompile/format the action
    secrets:
      PIPELINE_BOT_PAT: ${{ secrets.PIPELINE_BOT_PAT }}
