name: Increment Version on Merge
on:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # - GitHub’s standard pull_request workflow trigger prevents write permissions and secrets
  #   access to the target repository from public forks.  PRs from a branch in the same repo
  #   and forks of internal/private repos are not limited the same way for this trigger.
  # - The pull_request_target trigger allows the workflow to relax some restrictions to a
  #   target repository so PRs from forks have write permission to the target repo and have
  #   secrets access (which we need in order to push a new tag in this workflow).
  # - For this workflow, the elevated permissions should not be a problem because:
  #    - Require approval for all outside collaborators' is set at the org level so someone
  #      with Write access has a chance to review code before allowing any workflow runs
  #    - This workflow with elevated Write permissions will only run once the code has been
  #      reviewed, approved by a CODEOWNER and merged
  pull_request_target:
    types: [closed]
    paths:
      - 'action.yml'
      - 'package-lock.json'
      - 'package.json'
      - 'dist/**'
      - 'src/**'

jobs:
  increment-version:
    uses: im-open/.github/.github/workflows/reusable-version-on-merge.yml@v1
    with:
      default-branch: main
